# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='request_book',
            name='author',
            field=models.CharField(default='DUMMY', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
