# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20170309_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_book',
            name='author',
            field=models.CharField(default='dummy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='present_book',
            name='link',
            field=models.CharField(default='dummy', max_length=200),
            preserve_default=False,
        ),
    ]
