# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20170309_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_book',
            old_name='links',
            new_name='book_link',
        ),
    ]
